ext:
    path:
        resources: src/main/resources

spring:
    datasource:
        url: jdbc:mysql://localhost:3306/costaccount
        username: root
        password: lizhiyong
        driver-class-name: com.mysql.jdbc.Driver
    mvc:
        view:
            prefix: jsp 
            suffix: .jsp
        mvc:
            async:
                request-timeout: 20
            date-format: dd/MM/yyyy
            
    profiles:
        active: DEFAULT
    multipart:
        enabled: true
        file-size-threshold: 0
        location: 
        max-file-size: 50M
        max-request-size: 50M
    http:
        encoding:
            charset: UTF-8
        converters:
            preferred-json-mapper: true
    jackson:
        date-format: yyyy-MM-dd HH:mm:ss

# 服务器
server:
    #端口
    port: 8080
    #监听路径
    servlet-path: /
    session:
        timeout: 1800
    #压缩
    compression:
        #是否开启压缩
        enabled: true
    
# 安全
security:
    basic:
        enabled: false
        authorize-mode: 
        path: [/**]
        realm: 
    user:
        name: admin
        password: lizhiyong