ext:
    path:
        resources: src/main/resources

spring:
    datasource:
        url: jdbc:mysql://localhost:3306/costaccount?useUnicode=true&characterEncoding=UTF-8
        username: root
        password: 
        driver-class-name: com.mysql.jdbc.Driver
    profiles:
        active: DEFAULT
    multipart:
        enabled: true
        file-size-threshold: 0
        location: 
        max-file-size: 50M
        max-request-size: 50M
    http:
        encoding:
            charset: UTF-8
        converters:
            preferred-json-mapper: true
    session:
        store-type: none
    jackson:
        date-format: yyyy-MM-dd HH:mm:ss
    thymeleaf:
        cache: false
        mode: HTML

# 服务器
server:
    #端口
    port: 8080
    #监听路径
    servlet-path: /
    session:
        timeout: 1800
    #压缩
    compression:
        #是否开启压缩
        enabled: true
    
# 安全
security:
    basic:
        enabled: false
        authorize-mode: 
        path: [/**]
        realm: 
    user:
        name: admin
        password: lizhiyong